### ISSUE TITLE
Provider review

### ISSUE THREAD

**Issue by catsby** [f5devcentral/terraform-provider-bigip#1]
Hello! 

This is a copy-paste of a review originally posted to https://github.com/scshitole/terraform-provider-bigip/issues/2, for tracking progress.

------

Hello! 

My name is Clint, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and have some initial feedback on the current state. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the git commit 8c7e41d593f6715fa6e21c281d915b719f994c39 .

- [x] Please clean up the root directory of example files and the .terraform directory. The .terraform directory should be added to a .gitignore file. There are other files such as `1`, `~`, `README.md.swp`, a `terraform-provider-bigip` file that appears to be a binary, and `statefile` that need to be removed. In the `bigip` folder there appear to be backup files with `.goback` extensions that should be removed. If there are examples that should be included please move them to an `examples` directory and ensure they have a `.tf` file extension.
- [x] Please rename the `CHANGES.md` file to `CHANGELOG.md`
- [x] The building and installing instructions need to be updated (including the Makefile) to reflect modern Terraform. Many of the steps therein are not required. See the AWS Makefile for a guide 
- [x] Installation should be changed to encourage users to download and compile/install via the makefile, instead of downloading a binary from another GitHub organization. Understandably the instructions may not account for the newly desired way of using the provider, from within terraform itself and pulled from releases.hashicorp.com
- [x] There is no website directory. Please see the AWS provider as an example for the website structure and contents. The Provider and each resource / data source need to be documented in a directory `website`:. https://github.com/terraform-providers/terraform-provider-aws/tree/master/website 
- [x] I’m unable to compile the provider. I’ve attemted to use make commands but I’m getting errors. The Makefile is a great convenience utility, however `go build` should work as well.
- [x] Inadequate test coverage. Only 9 of the 41 files contained in the `bigip` implementation files are test files. Each resource and data source should have companion test file. 

That’s all for the initial first pass. If you believe I’ve misstated something please let me know! 

Cheers,
Clint

**Comment by scshitole** [comment]
Hello 
I have cleaned up repo as per the issue created, also added test files for the other modules. Working on the Make file will update with information.
Thanks

**Comment by scshitole** [comment]
> I’m unable to compile the provider. I’ve attemted to use make commands but I’m getting errors. The Makefile is a great convenience utility, however go build should work as well.

Cloning a clean copy of this repo and getting all deps using go get, `go build` works fine. Follow the instructions in this dep script to do a successful build please.

https://github.com/f5devcentral/terraform-provider-f5/blob/master/scripts/dep.sh

**Comment by scshitole** [comment]
@catsby 
Installation should be changed to encourage users to download and compile/install via the makefile, instead of downloading a binary from another GitHub organization. Understandably the instructions may not account for the newly desired way of using the provider, from within terraform itself and pulled from releases.hashicorp.com

Yes created makefile which builds the images, the images are in Release on github

**Comment by scshitole** [comment]
@catsby 
I’m unable to compile the provider. I’ve attemted to use make commands but I’m getting errors. The Makefile is a great convenience utility, however go build should work as well.

-Should be able to build the images now, earlier the repo name was f5, now changed to bigip.

**Comment by gliptak** [comment]
@catsby Please continue your review. Thanks

**Comment by catsby** [comment]
Thanks! I'm going to close this and open a new issue for tracking new feedback
