### ISSUE TITLE
bigip vs f5?

### ISSUE THREAD

**Issue by gliptak** [f5devcentral/terraform-provider-bigip#12]
The ```rootPath``` doesn't seem to be correct:

https://github.com/f5devcentral/terraform-provider-f5/blob/d1f2e27dbb991f9f5496278bfd4db1765b7754e1/vendor/vendor.json#L508

The documentation refers to ```bigip``` in numerous places while the project is named ```f5```. Should we consider renaming project to ```terraform-provider-bigip```?

Thanks

**Comment by scshitole** [comment]
Yes I think we should do that

**Comment by gliptak** [comment]
@scshitole I would  be happy to update my ```upstream``` at any time :)

**Comment by scshitole** [comment]
Thanks Sure I can merge into the master repo once done

**Comment by gliptak** [comment]
The thought would be to rename ```terraform-provider-f5``` -> ```terraform-provider-bigip``` in the https://github.com/f5devcentral console. After that I can submit renames in the source tree to correct builds.

**Comment by scshitole** [comment]
I renamed the repo to terraform-provider-bigip please submit renames in the
source tree

**Comment by gliptak** [comment]
https://github.com/f5devcentral/terraform-provider-bigip/pull/14

**Comment by gliptak** [comment]
Completed. Thanks @scshitole
