### ISSUE TITLE
go-bigip sources diverged

### ISSUE THREAD

**Issue by gliptak** [f5devcentral/terraform-provider-bigip#16]
In the ```vendor``` tree at

https://github.com/f5devcentral/terraform-provider-bigip/tree/master/vendor/github.com/scottdware/go-bigip

files were modified and new files were added, so it no longer matches

https://github.com/scottdware/go-bigip

Consider contributing those changes and new files to ```go-bigip``` project and we are to ```vendor``` to a current commit.

Or we could go the other way, and "merge in" sources from ```go-bigip``` and remove them from ```vendor```

Thanks

@scshitole

**Comment by gliptak** [comment]
@scshitole Please comment. Thanks

**Comment by gliptak** [comment]
Now ```vendor``` points to https://github.com/f5devcentral/go-bigip

I submitted https://github.com/f5devcentral/terraform-provider-bigip/pulls to bring ```vendor``` current.

**Comment by scshitole** [comment]
Thanks Gabor
