### ISSUE TITLE
allow-nat property of bigip_ltm_pool invalid

### ISSUE THREAD

**Issue by mattlqx** [f5devcentral/terraform-provider-bigip#36]
I'm not sure if this is from me running old software on my F5 or not, but...

Example terraform:
```
resource "bigip_ltm_pool" "managers-http" {
  name                = "/Common/${lower(var.env_type)}_manager_http"
  load_balancing_mode = "round-robin"
  nodes               = ["${formatlist("%s:80", bigip_ltm_node.manager.*.name)}"]
  monitors            = ["${bigip_ltm_monitor.http-monitor.name}"]
}
```

Results in this during apply:
```
Error applying plan:

1 error(s) occurred:

* bigip_ltm_pool.managers-http: 1 error(s) occurred:

* bigip_ltm_pool.managers-http: invalid property value "allow-nat":"1"
```

Setting explicitly setting `allow_nat = false` results in the same error (with 0 value obviously).

My F5 is running version BIG-IP 11.6.1 Build 0.0.317 Final and this is with version 0.3 of this provider.

**Comment by scshitole** [comment]
@mattlqx 
Please also include allow_snat = true, It needs allow_snat as well, please see below
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + bigip_ltm_pool.pool
      id:                  <computed>
      allow_nat:           "yes"
      allow_snat:          "yes"
      load_balancing_mode: "round-robin"
      monitors.#:          "1"
      monitors.1095875955: "/Common/terraform_monitor"
      name:                "/Common/terraform-pool"
      nodes.#:             "2"
      nodes.2872054492:    "11.1.1.101:80"
      nodes.3112549682:    "11.1.1.102:80"


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform apply
bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)
bigip_ltm_pool.pool: Creating...
  allow_nat:           "" => "yes"
  allow_snat:          "" => "yes"
  load_balancing_mode: "" => "round-robin"
  monitors.#:          "" => "1"
  monitors.1095875955: "" => "/Common/terraform_monitor"
  name:                "" => "/Common/terraform-pool"
  nodes.#:             "" => "2"
  nodes.2872054492:    "" => "11.1.1.101:80"
  nodes.3112549682:    "" => "11.1.1.102:80"
bigip_ltm_pool.pool: Creation complete after 0s (ID: /Common/terraform-pool)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$

**Comment by mattlqx** [comment]
Thank you for the quick response. It seems that the problem was actually using `true`/`false` rather than `'yes'`/`'no'`.

Having this still threw the error:
```
  allow_snat          = false
  allow_nat           = false
```

But using this works!
```
  allow_snat          = "no"
  allow_nat           = "no"
```

That is counter to the example here: https://github.com/f5devcentral/terraform-provider-bigip/blame/master/README.md#L122

**Comment by scshitole** [comment]
Yes  you are correct, allow_snat and allow_nat are fields taking string value instead of boolean. So instead of true and false  please refer to "yes" and "no"

**Comment by scshitole** [comment]
Will fix the documentation thanks for pointing out.
