### ISSUE TITLE
Provider review continued

### ISSUE THREAD

**Issue by catsby** [f5devcentral/terraform-provider-bigip#39]
Hello! I've taken another look, here's some more feedback:

deps.sh:
- are all the deps in deps.sh needed? Where are the AWS, go-radix and such used in this provider?
- for example, I had armon/go-radix installed locally. I removed it from machine, and ran `go build` and the BigIP provider built successfully
- github.com/posener/complete is for bash completion, how is that used in this ProvideR? 
- a script labeld deps probably shouldn't also build the binary, instead simply fetch necessary dependencies

It's fine to have a file like this to install dependencies needed to work on the provider, so long as all dependencies required to *build* the provider are in the vendor directory, placed there by govendor. 

Files that appear unneeded:

- get-pip.py
- examples/aws

GNUmakefile:

- the default should simply install the provider with `go install`. Currently, the default cross compiles BigIP for all platforms. We recommend that be moved to another command so it’s still available, but by default running make should simply install with “go install” for the platform it’s being ran on

Scripts:

- please copy over the changelog-links.sh, errcheck.sh, gofmtcheck.sh files from the AWS Provider:
  - https://github.com/terraform-providers/terraform-provider-aws/tree/master/scripts

Vendor dependencies:

I believe there’s a misconfiguration here. I recommend clearing out the vendor dependencies and redoing them. 

Currently many of them have an origin like “"origin": "github.com/hashicorp/terraform/vendor/github.com/[…]”, which implies they have been pulled from the Terraform project source? 

I recommend removing the directory, re-running “govendor init”  and then run “govendor fetch +out”, then committing the results. Verify the provider binary compiles successfully of course. 

Resources:

- There are 27 resources included, but I only see 22 resource test files. Each resource should have at least one basic acceptance test included.
- The following is an incomplete list resources have delete methods that are not implemented:
  - resource_bigip_cm_device
  - resource_bigip_cm_devicegroup
  - resource_bigip_device_name
  - resource_bigip_ltm_lic
- Please verify all resources have a delete method that correctly deletes the resource
- resource_bigip_ltm_snat and resource_bigip_net_vlan do not completely implement a READ method, they simply returns nil. Please make sure all resources READ from the API. 

Error checking:

- when deleting a resource (or checking if a resource is destroyed in an acceptance test), there should be error checking to determine if the error returned from an API call is of the nature of a 404, meaning that the resource that was being looked for , or attempted to destroy, does not exist. If these errors are found, then they are safe to remove from state or considered “expected errors” to ignore. Any other error should be reported. 

At this point I think I’ve listed several things to address before we continue. Please let me know if you have any questions about this feedback. Thanks!

**Comment by scshitole** [comment]
@catsby 
Files that appear unneeded:

get-pip.py
examples/aws

removed the above files


please copy over the changelog-links.sh, errcheck.sh, gofmtcheck.sh files from the AWS Provider:
https://github.com/terraform-providers/terraform-provider-aws/tree/master/scripts

updated the scripts directory with above files

**Comment by catsby** [comment]
Thanks for applying some of the feedback! Let us know when you have more to review!

**Comment by scshitole** [comment]
@catsby 
Thanks for reviewing, I have implemented delete methods and also test  files for resource_bigip_cm_device
resource_bigip_cm_devicegroup 

Test file for resource_bigip_cm_devicegroup is failing  not sure why ? spend almost 1 day trying to figure out any insights will help
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.192.74.73  TF_ACC=1 TF_DEBUG=1 go test ./bigip -v -run TestBigipCmdevicegroup_create
=== RUN   TestBigipCmdevicegroup_create
--- FAIL: TestBigipCmdevicegroup_create (0.33s)
	testing.go:513: Step 0 error: After applying this step and refreshing, the plan was not empty:
		
		DIFF:
		
		UPDATE: bigip_cm_devicegroup.test-devicegroup
		  auto_sync:         "" => "enabled"
		  full_load_on_sync: "" => "true"
		  name:              "test-devicegroup1" => "/Common/test-devicegroup1"
		  type:              "" => "sync-only"
		
		STATE:
		
		bigip_cm_devicegroup.test-devicegroup:
		  ID = /Common/test-devicegroup1
		  provider = provider.bigip
		  auto_sync = 
		  full_load_on_sync = 
		  name = test-devicegroup1
		  type =
FAIL
exit status 1


Also 
resource_bigip_ltm_snat and resource_bigip_net_vlan do not completely implement a READ method, they simply returns nil. Please make sure all resources READ from the API.

Implemented READ for both of the resources

**Comment by scshitole** [comment]
@catsby 
The above failure is fixed implemented proper read for the devicegroup resource and is working fine now. Also implemented test for the remaining resources. Resource bigip_ltm_policy and bigip_sys_lic is removed, will add later after the provider is published.

**Comment by scshitole** [comment]
@catsby 
Error checking:

when deleting a resource (or checking if a resource is destroyed in an acceptance test), there should be error checking to determine if the error returned from an API call is of the nature of a 404, meaning that the resource that was being looked for , or attempted to destroy, does not exist. If these errors are found, then they are safe to remove from state or considered “expected errors” to ignore. Any other error should be reported.

- Error handling is done in https://github.com/f5devcentral/terraform-provider-bigip/blob/master/vendor/github.com/f5devcentral/go-bigip/bigip.go


// Error returns the error message.
func (r *RequestError) Error() error {
	if r.Message != "" {
		return errors.New(r.Message)
	}

	return nil

func (b *BigIP) getForEntity(e interface{}, path ...string) (error, bool) {
	req := &APIRequest{
		Method:      "get",
		URL:         b.iControlPath(path),
		ContentType: "application/json",
	}

	resp, err := b.APICall(req)
	if err != nil {
		var reqError RequestError
		json.Unmarshal(resp, &reqError)
		if reqError.Code == 404 {
			return nil, false
		}
		return err, false
	}

So if the resource does not exists it reports appropriately for example

Error: Error applying plan:

1 error(s) occurred:

* bigip_cm_devicegroup.my_new_devicegroup (destroy): 1 error(s) occurred:

* bigip_cm_devicegroup.my_new_devicegroup: 01020036:3: The requested device group (/Common/deadlygroup) was not found.

**Comment by catsby** [comment]
I'm not sure the error handling I'm seeing is appropriate here. 
What I meant above was that, when Terraform calls it's READ method on a Resource, if the subsequent API call returns a 404 error or equivalent, then Terraform needs to remove the item from state.

And example can be found in the AWS Provider, Resource `db_parameter_group`:

https://github.com/terraform-providers/terraform-provider-aws/blob/1507f6c0315a5b5c3090b3d30863edefc3236f39/aws/resource_aws_db_parameter_group.go#L128-L143

I'm not sure I understand the example you gave. Take the `resource_bigip_ltm_irule` resource: 

https://github.com/f5devcentral/terraform-provider-bigip/blob/296928c3beacb1ace30bf9804c43a13108bbeae5/bigip/resource_bigip_ltm_irule.go#L56-L68

This READ method calls `client.IRule(name)`. That method calls the internal method `getForEntity()` to call the API, which is defined like so:

https://github.com/f5devcentral/go-bigip/blob/d7fcba783d41b1b862ea9b05ed80e0c24dc0d253/bigip.go#L269-L292

In the `IRule()` method, if it receives `nil, false`, it then returns `nil, nil`:

https://github.com/f5devcentral/go-bigip/blob/d7fcba783d41b1b862ea9b05ed80e0c24dc0d253/ltm.go#L2436-L2446

Looking back at `resourceBigipLtmIRuleRead` above, the line `irule, err := client.IRule(name)` then results in both `irule` and `err` being `nil`, at which point I believe the Terraform Provider will panic as it tries to reference `irule.Rule` in the subsequent lines.

I don't believe the SDK should filter out 404 responses, instead Terraform should inspect the full error returned and behaving as a Terraform resource should, and in the case of this read method, that would be to remove from state and log the remove as shown in `db_parameter_group`. 

Does that clarify what I meant by error checking? 

Thanks!

**Comment by scshitole** [comment]
@catsby 
thanks got it will make those changes

**Comment by ericzji** [comment]
`
            if node == nil {
                        log.Printf("[WARN] Node (%s) not found, removing from state", d.Id())
                        d.SetId("")
                        return nil
            }`

**Comment by ericzji** [comment]
```

            if node == nil {
                        log.Printf("[WARN] Node (%s) not found, removing from state", d.Id())
                        d.SetId("")
                        return nil
            }
```

**Comment by ericzji** [comment]
https://github.com/f5devcentral/terraform-provider-bigip/blob/296928c3beacb1ace30bf9804c43a13108bbeae5/bigip/resource_bigip_ltm_irule.go#L56-L68

**Comment by ericzji** [comment]
Hi @catsby, 
Added a piece of code to resource_bigip_ltm_node.go to handle the case when node, err := client.GetNode(name) returns nil and nil. In this case, we will remove it from state and log the remove, and return to avoid the provider panic.

Here is the code change:
https://github.com/ericzji/terraform-provider-bigip/blob/ff544ef28468524411d478300756b9dd4c919ca4/bigip/resource_bigip_ltm_node.go#L65-L87

Also I tested the scenario with testing log attached:
https://gist.github.com/ericzji/7f2dd27b7619fcc675a38b84b415fbae

@catsby would please confirm this is the fix you are looking for. Upon confirmation, we can add the error handling for all BIG-IP resources.

thanks
-Eric

**Comment by ericzji** [comment]
https://github.com/ericzji/terraform-provider-bigip/blob/ff544ef28468524411d478300756b9dd4c919ca4/bigip/resource_bigip_ltm_node.go#L65-L87

**Comment by ericzji** [comment]
https://github.com/ericzji/terraform-provider-bigip/blob/ff544ef28468524411d478300756b9dd4c919ca4/bigip/resource_bigip_ltm_node.go#L77-L81

**Comment by ericzji** [comment]
@catsby Any feedback? thanks.

**Comment by catsby** [comment]
@ericzji sorry for the delay; yes, that's is the type of error handling I'm looking for in regards to both reading resources that are no longer there, as well as deleting them. Both scenarios should log the "not found" of the resource and then remove them from state, so that the user is not blocked on resources that no longer exist

**Comment by scshitole** [comment]
@catsby 
Thanks will implement the changes and update you soon !

**Comment by scshitole** [comment]
@catsby 
I have added the error correction checks to all the resources for read and delete. Please review the same.

**Comment by catsby** [comment]
Majority of the items mentioned here seem to be addressed! Thank you. I've opened #59 to continue the discussion, we're in the final stages I would think.
