### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by deln2403** [f5devcentral/terraform-provider-bigip#43]
providers {
  bigip = "/path/to/terraform-provider-bigip"
}
results in: failed to read provider plugin /path/to/terraform-provider-bigip: read /path/to/terraform-provider-bigip: is a directory

this works
bigip = "/path/to/terraform-provider-bigip/bigip/provider.go"

should this be added to the documentation?

**Comment by scshitole** [comment]
Thanks updated the path in documentation.

**Comment by deln2403** [comment]
hi @scshitole my previous comment was probably wrong. Maybe that change should be reverted.

I was pointing to the src code, not the binary.

Does the release package not include compiled binaries? I am struggling to compile myself. 

$ make bin
./main.go:10:15: cannot use "github.com/f5devcentral/terraform-provider-bigip/bigip".Provider (type func() "github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
# _/home/sysops/terraform-provider-bigip-0.3/bigip
bigip/resource_bigip_device.go:60:15: client.CreateDevice undefined (type *bigip.BigIP has no field or method CreateDevice)
bigip/resource_bigip_device.go:81:8: undefined: bigip.Device
bigip/resource_bigip_device.go:88:15: client.ModifyDevice undefined (type *bigip.BigIP has no field or method ModifyDevice)
bigip/resource_bigip_device.go:98:24: client.Devices undefined (type *bigip.BigIP has no field or method Devices)
bigip/resource_bigip_device_name.go:53:15: client.CreateDevicename undefined (type *bigip.BigIP has no field or method CreateDevicename)
bigip/resource_bigip_device_name.go:73:8: undefined: bigip.Devicename
bigip/resource_bigip_device_name.go:79:15: client.ModifyDevicename undefined (type *bigip.BigIP has no field or method ModifyDevicename)
bigip/resource_bigip_device_name.go:89:24: client.Devicenames undefined (type *bigip.BigIP has no field or method Devicenames)
bigip/resource_bigip_devicegroup.go:59:15: client.CreateDevicegroup undefined (type *bigip.BigIP has no field or method CreateDevicegroup)
bigip/resource_bigip_devicegroup.go:80:8: undefined: bigip.Devicegroup
bigip/resource_bigip_devicegroup.go:80:8: too many errors
make: *** [build] Error 2

$ go build -o terraform-provider-bigip
./main.go:10:15: cannot use "github.com/f5devcentral/terraform-provider-bigip/bigip".Provider (type func() "github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value


any advice?
