### ISSUE TITLE
Release compiled binaries

### ISSUE THREAD

**Issue by deln2403** [f5devcentral/terraform-provider-bigip#44]
Please release compiled modules or provide more detailed steps to compile code. Currently only source code is available in your release package.

Example from DealerDotCom/terraform-provider-bigip
![image](https://user-images.githubusercontent.com/5318775/34534199-42866d14-f08b-11e7-8a8e-ccbabd97c1a0.png)

**Comment by scshitole** [comment]
@deln2403 
To compile your self please follow below instructions 
SJC-ML-SHITOLE:~ shitole$ mkdir -p ecs-user/src/github.com/f5devcentral
SJC-ML-SHITOLE:~ shitole$ cd ecs-user/
SJC-ML-SHITOLE:ecs-user shitole$ GOPATH=$HOME/ecs-user
SJC-ML-SHITOLE:ecs-user shitole$ go get github.com/f5devcentral/terraform-provider-bigip/bigip
SJC-ML-SHITOLE:ecs-user shitole$ ls
pkg	src
SJC-ML-SHITOLE:ecs-user shitole$ cd src/
SJC-ML-SHITOLE:src shitole$ ls
github.com
SJC-ML-SHITOLE:src shitole$ cd github.com/f5devcentral/terraform-provider-bigip/
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ cd examples
SJC-ML-SHITOLE:examples shitole$ cp master.tf ../.
SJC-ML-SHITOLE:examples shitole$ cd ..

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ cat master.tf
provider "bigip" {
  address = "10.192.74.61"
  username = "admin"
  password = "admin"
}


resource "bigip_sys_provision" "provision-afm" {
  name = "/Common/afm"
  full_path  = "afm"
  cpu_ratio = 0
  disk_ratio = 0
  level = "nominal"
  memory_ratio = 0
}

resource "bigip_sys_ntp" "ntp1" {
  	description = "/Common/NTP1"
  	servers = ["time.google.com"]
  	timezone = "America/Los_Angeles"
	depends_on = ["bigip_sys_provision.provision-afm"]
}

resource "bigip_sys_dns" "dns1" {
   	description = "/Common/DNS1"
   	name_servers = ["8.8.8.8"]
   	numberof_dots = 2
   	search = ["f5.com"]
   	depends_on = ["bigip_sys_provision.provision-afm"]
}
resource "bigip_net_vlan" "vlan1" {
	name = "/Common/internal"
	tag = 101
	interfaces = {
		vlanport = 1.2,
		tagged = false
	}	

        depends_on = ["bigip_sys_provision.provision-afm"]
}

resource "bigip_net_vlan" "vlan2" {
        name = "/Common/external"
        tag = 102
        interfaces = {
                vlanport = 1.1,
                tagged = false
        }

        depends_on = ["bigip_sys_provision.provision-afm"]
}

resource "bigip_net_selfip" "selfip1" {
	name = "/Common/internalselfIP"
	ip = "11.1.1.1/24"
	vlan = "/Common/internal"
	depends_on = ["bigip_net_vlan.vlan1"]
        depends_on = ["bigip_sys_provision.provision-afm"]
	}

resource "bigip_net_selfip" "selfip2" {
        name = "/Common/externalselfIP"
        ip = "100.1.1.1/24"
        vlan = "/Common/external"
        depends_on = ["bigip_net_vlan.vlan2"]
        depends_on = ["bigip_sys_provision.provision-afm"]
        }


resource "bigip_ltm_monitor" "monitor" {
        name = "/Common/terraform_monitor"
        parent = "/Common/http"
        send = "GET /some/path\r\n"
        timeout = "999"
        interval = "999"
        depends_on = ["bigip_sys_provision.provision-afm"]
}

resource "bigip_ltm_pool"  "pool" {
        name = "/Common/terraform-pool"
        load_balancing_mode = "round-robin"
        nodes = ["11.1.1.101:80", "11.1.1.102:80"]
        monitors = ["/Common/terraform_monitor"]
        allow_snat = "yes"
        allow_nat = "yes"
        depends_on = ["bigip_sys_provision.provision-afm"]
}

resource "bigip_ltm_virtual_server" "http" {
	pool = "/Common/terraform-pool"
        name = "/Common/terraform_vs_http"
	destination = "100.1.1.100"
	port = 80
	source_address_translation = "automap"
        depends_on = ["bigip_ltm_pool.pool"]
}


SJC-ML-SHITOLE:terraform-provider-bigip shitole$ vi master.tf
SJC-ML-SHITOLE:terraform-provider-bigip shitole$
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ pwd
/Users/shitole/ecs-user/src/github.com/f5devcentral/terraform-provider-bigip
SJC-ML-SHITOLE:terraform-provider-bigip shitole$
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ go build
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

**Comment by deln2403** [comment]
Thank you @scshitole !

allow me to suggest a shorter version:

```
# create working dir
export GOPATH=$HOME/workspace
mkdir -p $GOPATH/src/github.com/f5devcentral && cd $GOPATH

# get source code
go get github.com/f5devcentral/terraform-provider-bigip

# build and move bin into plugin folder
cd src/github.com/f5devcentral/terraform-provider-bigip/
go build
PLUGIN_DIR=$HOME/.terraform.d/plugins/linux_amd64/
mkdir -p $PLUGIN_DIR && cp terraform-provider-bigip $PLUGIN_DIR/

cat > $HOME/.terraformrc <<- EOM
providers {
  bigip = "$HOME/.terraform.d/plugins/linux_amd64/terraform-provider-bigip"
}
EOM

...

# init
$ terraform init
```
