### ISSUE TITLE
Choice of the type of vs

### ISSUE THREAD

**Issue by doe35** [f5devcentral/terraform-provider-bigip#45]
Good job, that's exactly the type of tool I was looking for.

Nevertheless, it seems that we do not have the choice of the type of vs (Layer 4/Standard/Forwarding).

Created VS are systematically in Performance (Layer 4)

Thanks

**Comment by mattlqx** [comment]
The type is related to the profile specified. If you want standard, select a client profile of "tcp" or a variant. Layer 4 is the same as Forwarding except with options for destination address and port translation, as far as I know.

**Comment by doe35** [comment]
Thanks for you reply. 
In fact, by selecting "TCP" or "UDP", virtual server become standard

Thanks for all
