### ISSUE TITLE
No LTM resource for Policies

### ISSUE THREAD

**Issue by lampwins** [f5devcentral/terraform-provider-bigip#46]
Hello and great work on this!

I noticed this seems to be a a more advanced fork of https://github.com/DealerDotCom/terraform-provider-bigip. However, I noticed in this repo, there is no resource for ltm policies, despite there being an example in the readme. Are there plans to bring this resource over, or a reason it was not? Is this something you would be open to a PR on?

**Comment by scshitole** [comment]
@lampwins 
Thanks for your comments Its in works as you speak, will remove from the README time being we are adding lot of resources like policy, iApp, GTM and actively working on the same.

**Comment by st33v** [comment]
I also had problems with the DealerDotCom provider not supporting 'cookie policies'. I can set a 'policy' but not a 'cookie policy'. Seems like the underlying golang f5 library doesn't support it so it makes sense that the provider wouldn't either. It's a show stopper for us.

I have to say that I'm CRAZY excited that f5 has taken up the development of this provider.

**Comment by scshitole** [comment]
@st33v Thanks for the feedback, I have implemented iApps (Application Services) recently, now you can deploy iApps as well using terraform.

**Comment by scshitole** [comment]
@lampwins LTM resource is added
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ cat master.tf
provider "bigip" {
  address = "10.192.74.73"
  username = "admin"
  password = "admin"
}

resource "bigip_ltm_policy" "test-policy" {
 name = "my_policy"
 strategy = "first-match"
  requires = ["http"]
 published_copy = "Drafts/my_policy"
  controls = ["forwarding"]
  rule  {
  name = "rule6"

   action = {
     tm_name = "20"
     forward = true
      pool = "/Common/mypool"
   }
  }
depends_on = ["bigip_ltm_pool.mypool"]
}

resource "bigip_ltm_node" "sanjose_node" {
    name = "/Common/sanjose_node"
    address = "10.10.10.10"
}
resource "bigip_ltm_pool" "mypool" {
    name = "/Common/mypool"
    monitors = ["/Common/http"]
    allow_nat = "yes"
    allow_snat = "yes"
    load_balancing_mode = "round-robin"
    depends_on = ["bigip_ltm_node.sanjose_node"]
    nodes = ["sanjose_node:443"]
}
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + bigip_ltm_node.sanjose_node
      id:                                   <computed>
      address:                              "10.10.10.10"
      name:                                 "/Common/sanjose_node"

  + bigip_ltm_policy.test-policy
      id:                                   <computed>
      controls.#:                           "1"
      controls.3762513669:                  "forwarding"
      name:                                 "my_policy"
      published_copy:                       "Drafts/my_policy"
      requires.#:                           "1"
      requires.2541227442:                  "http"
      rule.#:                               "1"
      rule.0.action.#:                      "1"
      rule.0.action.0.app_service:          <computed>
      rule.0.action.0.application:          <computed>
      rule.0.action.0.asm:                  <computed>
      rule.0.action.0.avr:                  <computed>
      rule.0.action.0.cache:                <computed>
      rule.0.action.0.carp:                 <computed>
      rule.0.action.0.category:             <computed>
      rule.0.action.0.classify:             <computed>
      rule.0.action.0.clone_pool:           <computed>
      rule.0.action.0.code:                 <computed>
      rule.0.action.0.compress:             <computed>
      rule.0.action.0.content:              <computed>
      rule.0.action.0.cookie_hash:          <computed>
      rule.0.action.0.cookie_insert:        <computed>
      rule.0.action.0.cookie_passive:       <computed>
      rule.0.action.0.cookie_rewrite:       <computed>
      rule.0.action.0.decompress:           <computed>
      rule.0.action.0.defer:                <computed>
      rule.0.action.0.destination_address:  <computed>
      rule.0.action.0.disable:              <computed>
      rule.0.action.0.domain:               <computed>
      rule.0.action.0.enable:               <computed>
      rule.0.action.0.expiry:               <computed>
      rule.0.action.0.expiry_secs:          <computed>
      rule.0.action.0.expression:           <computed>
      rule.0.action.0.extension:            <computed>
      rule.0.action.0.facility:             <computed>
      rule.0.action.0.forward:              "true"
      rule.0.action.0.from_profile:         <computed>
      rule.0.action.0.hash:                 <computed>
      rule.0.action.0.host:                 <computed>
      rule.0.action.0.http:                 <computed>
      rule.0.action.0.http_basic_auth:      <computed>
      rule.0.action.0.http_cookie:          <computed>
      rule.0.action.0.http_header:          <computed>
      rule.0.action.0.http_referer:         <computed>
      rule.0.action.0.http_reply:           <computed>
      rule.0.action.0.http_set_cookie:      <computed>
      rule.0.action.0.http_uri:             <computed>
      rule.0.action.0.ifile:                <computed>
      rule.0.action.0.insert:               <computed>
      rule.0.action.0.internal_virtual:     <computed>
      rule.0.action.0.ip_address:           <computed>
      rule.0.action.0.key:                  <computed>
      rule.0.action.0.l7dos:                <computed>
      rule.0.action.0.length:               <computed>
      rule.0.action.0.location:             <computed>
      rule.0.action.0.log:                  <computed>
      rule.0.action.0.ltm_policy:           <computed>
      rule.0.action.0.member:               <computed>
      rule.0.action.0.message:              <computed>
      rule.0.action.0.netmask:              <computed>
      rule.0.action.0.nexthop:              <computed>
      rule.0.action.0.node:                 <computed>
      rule.0.action.0.offset:               <computed>
      rule.0.action.0.path:                 <computed>
      rule.0.action.0.pem:                  <computed>
      rule.0.action.0.persist:              <computed>
      rule.0.action.0.pin:                  <computed>
      rule.0.action.0.policy:               <computed>
      rule.0.action.0.pool:                 "/Common/mypool"
      rule.0.action.0.port:                 <computed>
      rule.0.action.0.priority:             <computed>
      rule.0.action.0.profile:              <computed>
      rule.0.action.0.protocol:             <computed>
      rule.0.action.0.query_string:         <computed>
      rule.0.action.0.rateclass:            <computed>
      rule.0.action.0.redirect:             <computed>
      rule.0.action.0.remove:               <computed>
      rule.0.action.0.replace:              <computed>
      rule.0.action.0.request:              <computed>
      rule.0.action.0.request_adapt:        <computed>
      rule.0.action.0.reset:                <computed>
      rule.0.action.0.response:             <computed>
      rule.0.action.0.response_adapt:       <computed>
      rule.0.action.0.scheme:               <computed>
      rule.0.action.0.script:               <computed>
      rule.0.action.0.select:               <computed>
      rule.0.action.0.server_ssl:           <computed>
      rule.0.action.0.set_variable:         <computed>
      rule.0.action.0.snat:                 <computed>
      rule.0.action.0.snatpool:             <computed>
      rule.0.action.0.source_address:       <computed>
      rule.0.action.0.ssl_client_hello:     <computed>
      rule.0.action.0.ssl_server_handshake: <computed>
      rule.0.action.0.ssl_server_hello:     <computed>
      rule.0.action.0.ssl_session_id:       <computed>
      rule.0.action.0.status:               <computed>
      rule.0.action.0.tcl:                  <computed>
      rule.0.action.0.tcp_nagle:            <computed>
      rule.0.action.0.text:                 <computed>
      rule.0.action.0.timeout:              <computed>
      rule.0.action.0.tm_name:              "20"
      rule.0.action.0.uie:                  <computed>
      rule.0.action.0.universal:            <computed>
      rule.0.action.0.value:                <computed>
      rule.0.action.0.virtual:              <computed>
      rule.0.action.0.vlan:                 <computed>
      rule.0.action.0.vlan_id:              <computed>
      rule.0.action.0.wam:                  <computed>
      rule.0.action.0.write:                <computed>
      rule.0.name:                          "rule6"
      strategy:                             "first-match"

  + bigip_ltm_pool.mypool
      id:                                   <computed>
      allow_nat:                            "yes"
      allow_snat:                           "yes"
      load_balancing_mode:                  "round-robin"
      monitors.#:                           "1"
      monitors.576276785:                   "/Common/http"
      name:                                 "/Common/mypool"
      nodes.#:                              "1"
      nodes.4148154080:                     "sanjose_node:443"


Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_node.sanjose_node: Creating...
  address: "" => "10.10.10.10"
  name:    "" => "/Common/sanjose_node"
bigip_ltm_node.sanjose_node: Creation complete after 0s (ID: /Common/sanjose_node)
bigip_ltm_pool.mypool: Creating...
  allow_nat:           "" => "yes"
  allow_snat:          "" => "yes"
  load_balancing_mode: "" => "round-robin"
  monitors.#:          "" => "1"
  monitors.576276785:  "" => "/Common/http"
  name:                "" => "/Common/mypool"
  nodes.#:             "" => "1"
  nodes.4148154080:    "" => "sanjose_node:443"
bigip_ltm_pool.mypool: Creation complete after 0s (ID: /Common/mypool)
bigip_ltm_policy.test-policy: Creating...
  controls.#:                           "" => "1"
  controls.3762513669:                  "" => "forwarding"
  name:                                 "" => "my_policy"
  published_copy:                       "" => "Drafts/my_policy"
  requires.#:                           "" => "1"
  requires.2541227442:                  "" => "http"
  rule.#:                               "" => "1"
  rule.0.action.#:                      "" => "1"
  rule.0.action.0.app_service:          "" => "<computed>"
  rule.0.action.0.application:          "" => "<computed>"
  rule.0.action.0.asm:                  "" => "<computed>"
  rule.0.action.0.avr:                  "" => "<computed>"
  rule.0.action.0.cache:                "" => "<computed>"
  rule.0.action.0.carp:                 "" => "<computed>"
  rule.0.action.0.category:             "" => "<computed>"
  rule.0.action.0.classify:             "" => "<computed>"
  rule.0.action.0.clone_pool:           "" => "<computed>"
  rule.0.action.0.code:                 "" => "<computed>"
  rule.0.action.0.compress:             "" => "<computed>"
  rule.0.action.0.content:              "" => "<computed>"
  rule.0.action.0.cookie_hash:          "" => "<computed>"
  rule.0.action.0.cookie_insert:        "" => "<computed>"
  rule.0.action.0.cookie_passive:       "" => "<computed>"
  rule.0.action.0.cookie_rewrite:       "" => "<computed>"
  rule.0.action.0.decompress:           "" => "<computed>"
  rule.0.action.0.defer:                "" => "<computed>"
  rule.0.action.0.destination_address:  "" => "<computed>"
  rule.0.action.0.disable:              "" => "<computed>"
  rule.0.action.0.domain:               "" => "<computed>"
  rule.0.action.0.enable:               "" => "<computed>"
  rule.0.action.0.expiry:               "" => "<computed>"
  rule.0.action.0.expiry_secs:          "" => "<computed>"
  rule.0.action.0.expression:           "" => "<computed>"
  rule.0.action.0.extension:            "" => "<computed>"
  rule.0.action.0.facility:             "" => "<computed>"
  rule.0.action.0.forward:              "" => "true"
  rule.0.action.0.from_profile:         "" => "<computed>"
  rule.0.action.0.hash:                 "" => "<computed>"
  rule.0.action.0.host:                 "" => "<computed>"
  rule.0.action.0.http:                 "" => "<computed>"
  rule.0.action.0.http_basic_auth:      "" => "<computed>"
  rule.0.action.0.http_cookie:          "" => "<computed>"
  rule.0.action.0.http_header:          "" => "<computed>"
  rule.0.action.0.http_referer:         "" => "<computed>"
  rule.0.action.0.http_reply:           "" => "<computed>"
  rule.0.action.0.http_set_cookie:      "" => "<computed>"
  rule.0.action.0.http_uri:             "" => "<computed>"
  rule.0.action.0.ifile:                "" => "<computed>"
  rule.0.action.0.insert:               "" => "<computed>"
  rule.0.action.0.internal_virtual:     "" => "<computed>"
  rule.0.action.0.ip_address:           "" => "<computed>"
  rule.0.action.0.key:                  "" => "<computed>"
  rule.0.action.0.l7dos:                "" => "<computed>"
  rule.0.action.0.length:               "" => "<computed>"
  rule.0.action.0.location:             "" => "<computed>"
  rule.0.action.0.log:                  "" => "<computed>"
  rule.0.action.0.ltm_policy:           "" => "<computed>"
  rule.0.action.0.member:               "" => "<computed>"
  rule.0.action.0.message:              "" => "<computed>"
  rule.0.action.0.netmask:              "" => "<computed>"
  rule.0.action.0.nexthop:              "" => "<computed>"
  rule.0.action.0.node:                 "" => "<computed>"
  rule.0.action.0.offset:               "" => "<computed>"
  rule.0.action.0.path:                 "" => "<computed>"
  rule.0.action.0.pem:                  "" => "<computed>"
  rule.0.action.0.persist:              "" => "<computed>"
  rule.0.action.0.pin:                  "" => "<computed>"
  rule.0.action.0.policy:               "" => "<computed>"
  rule.0.action.0.pool:                 "" => "/Common/mypool"
  rule.0.action.0.port:                 "" => "<computed>"
  rule.0.action.0.priority:             "" => "<computed>"
  rule.0.action.0.profile:              "" => "<computed>"
  rule.0.action.0.protocol:             "" => "<computed>"
  rule.0.action.0.query_string:         "" => "<computed>"
  rule.0.action.0.rateclass:            "" => "<computed>"
  rule.0.action.0.redirect:             "" => "<computed>"
  rule.0.action.0.remove:               "" => "<computed>"
  rule.0.action.0.replace:              "" => "<computed>"
  rule.0.action.0.request:              "" => "<computed>"
  rule.0.action.0.request_adapt:        "" => "<computed>"
  rule.0.action.0.reset:                "" => "<computed>"
  rule.0.action.0.response:             "" => "<computed>"
  rule.0.action.0.response_adapt:       "" => "<computed>"
  rule.0.action.0.scheme:               "" => "<computed>"
  rule.0.action.0.script:               "" => "<computed>"
  rule.0.action.0.select:               "" => "<computed>"
  rule.0.action.0.server_ssl:           "" => "<computed>"
  rule.0.action.0.set_variable:         "" => "<computed>"
  rule.0.action.0.snat:                 "" => "<computed>"
  rule.0.action.0.snatpool:             "" => "<computed>"
  rule.0.action.0.source_address:       "" => "<computed>"
  rule.0.action.0.ssl_client_hello:     "" => "<computed>"
  rule.0.action.0.ssl_server_handshake: "" => "<computed>"
  rule.0.action.0.ssl_server_hello:     "" => "<computed>"
  rule.0.action.0.ssl_session_id:       "" => "<computed>"
  rule.0.action.0.status:               "" => "<computed>"
  rule.0.action.0.tcl:                  "" => "<computed>"
  rule.0.action.0.tcp_nagle:            "" => "<computed>"
  rule.0.action.0.text:                 "" => "<computed>"
  rule.0.action.0.timeout:              "" => "<computed>"
  rule.0.action.0.tm_name:              "" => "20"
  rule.0.action.0.uie:                  "" => "<computed>"
  rule.0.action.0.universal:            "" => "<computed>"
  rule.0.action.0.value:                "" => "<computed>"
  rule.0.action.0.virtual:              "" => "<computed>"
  rule.0.action.0.vlan:                 "" => "<computed>"
  rule.0.action.0.vlan_id:              "" => "<computed>"
  rule.0.action.0.wam:                  "" => "<computed>"
  rule.0.action.0.write:                "" => "<computed>"
  rule.0.name:                          "" => "rule6"
  strategy:                             "" => "first-match"
bigip_ltm_policy.test-policy: Creation complete after 0s (ID: my_policy)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$
