### ISSUE TITLE
Unable to set "VLAN and Tunnel Traffic" on VirtualServer

### ISSUE THREAD

**Issue by deln2403** [f5devcentral/terraform-provider-bigip#52]
Mapping a VLAN to a VirtualServer sets the "VLAN and Tunnel Traffic" property to "Disabled on..." by default. Is there a way to set it to "Enabled on..." ?

**Comment by scshitole** [comment]
@deln2403 Added vlans_enabled & vlans_disabled

resource "bigip_ltm_virtual_server" "http" {
	pool = "/Common/terraform-pool"
        name = "/Common/terraform_vs_http"
	destination = "100.1.1.100"
	port = 80
	source_address_translation = "automap"
        vlans_enabled = true
}

**Comment by deln2403** [comment]
awesome.
