### ISSUE TITLE
Update IP of existing node

### ISSUE THREAD

**Issue by deln2403** [f5devcentral/terraform-provider-bigip#53]
Updating the up of an existing node fails if the node is member of a pool (which it usually will be).

Error: Error applying plan:

1 error(s) occurred:

* bigip_ltm_node.node (destroy): 1 error(s) occurred:

* bigip_ltm_node.node: 01070110:3: Node address '/partition/nodename' is referenced by a member of pool '/partition/some_pool_web_80_pool'.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by deln2403** [comment]
Could the provide remove the node from the pool, update the ip (destroy/create if necessary) and then re-add?

**Comment by scshitole** [comment]
@deln2403 
I dont see the problem, 
1. I did terraform apply
2. Terraform plan 
3. Edited the node to 12.1.1.1 from 11.1.1.101
4, Did terraform apply and the changes were reflected

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + bigip_ltm_pool.pool
      id:                  <computed>
      allow_nat:           "yes"
      allow_snat:          "yes"
      load_balancing_mode: "round-robin"
      name:                "/Common/terraform-pool"
      nodes.#:             "2"
      nodes.2872054492:    "11.1.1.101:80"
      nodes.3112549682:    "11.1.1.102:80"


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + bigip_ltm_pool.pool
      id:                  <computed>
      allow_nat:           "yes"
      allow_snat:          "yes"
      load_balancing_mode: "round-robin"
      name:                "/Common/terraform-pool"
      nodes.#:             "2"
      nodes.2872054492:    "11.1.1.101:80"
      nodes.3112549682:    "11.1.1.102:80"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_pool.pool: Creating...
  allow_nat:           "" => "yes"
  allow_snat:          "" => "yes"
  load_balancing_mode: "" => "round-robin"
  name:                "" => "/Common/terraform-pool"
  nodes.#:             "" => "2"
  nodes.2872054492:    "" => "11.1.1.101:80"
  nodes.3112549682:    "" => "11.1.1.102:80"
bigip_ltm_pool.pool: Creation complete after 2s (ID: /Common/terraform-pool)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ vi master.tf 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ bigip_ltm_pool.pool
      nodes.2872054492: "11.1.1.101:80" => ""
      nodes.3112549682: "11.1.1.102:80" => "11.1.1.102:80"
      nodes.3702439980: "" => "12.1.1.101:80"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform apply
bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ bigip_ltm_pool.pool
      nodes.2872054492: "11.1.1.101:80" => ""
      nodes.3112549682: "11.1.1.102:80" => "11.1.1.102:80"
      nodes.3702439980: "" => "12.1.1.101:80"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_pool.pool: Modifying... (ID: /Common/terraform-pool)
  nodes.2872054492: "11.1.1.101:80" => ""
  nodes.3112549682: "11.1.1.102:80" => "11.1.1.102:80"
  nodes.3702439980: "" => "12.1.1.101:80"
bigip_ltm_pool.pool: Modifications complete after 2s (ID: /Common/terraform-pool)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform destroy
bigip_ltm_pool.pool: Refreshing state... (ID: /Common/terraform-pool)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - bigip_ltm_pool.pool


Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

bigip_ltm_pool.pool: Destroying... (ID: /Common/terraform-pool)
bigip_ltm_pool.pool: Destruction complete after 1s

Destroy complete! Resources: 1 destroyed.
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$

**Comment by scshitole** [comment]
@deln2403 
Is it possible to share your .TF file which fails

**Comment by deln2403** [comment]
don't have time to troubleshoot right now. I'll reach out again if needed later. Thanks @scshitole
