### ISSUE TITLE
Release distributable packages

### ISSUE THREAD

**Issue by bpoland** [f5devcentral/terraform-provider-bigip#55]
Hi there,

Are there any plans to build and release versioned packages that can be used directly with Terraform?  Like these ones for the other provider: https://github.com/DealerDotCom/terraform-provider-bigip/releases

Thanks!

**Comment by scshitole** [comment]
@bpoland we are planning to publish the provider with HashiCorp, so once the provider is published you wont need the binary.

**Comment by bpoland** [comment]
Oh great! Any idea when that will happen?

**Comment by scshitole** [comment]
@bpoland currently they are reviewing the code, it may happen in 2 -3 weeks time, meanwhile if you need the binary you can follow the below steps to compile your self
# create working dir
export GOPATH=$HOME/workspace
mkdir -p $GOPATH/src/github.com/f5devcentral && cd $GOPATH

# get source code
go get github.com/f5devcentral/terraform-provider-bigip

# build and move bin into plugin folder
cd src/github.com/f5devcentral/terraform-provider-bigip/
go build
PLUGIN_DIR=$HOME/.terraform.d/plugins/linux_amd64/
mkdir -p $PLUGIN_DIR && cp terraform-provider-bigip $PLUGIN_DIR/

cat > $HOME/.terraformrc <<- EOM
providers {
  bigip = "$HOME/.terraform.d/plugins/linux_amd64/terraform-provider-bigip"
}
EOM

...

# init
$ terraform init

**Comment by bpoland** [comment]
Ok thank you!
