### ISSUE TITLE
persistence_profiles attribute undocumented

### ISSUE THREAD

**Issue by curator** [f5devcentral/terraform-provider-bigip#64]
The `persistence_profiles` attribute (and related attributes) of the `bigip_ltm_virtual_server` resource are not yet documented, but are super useful.

**Comment by scshitole** [comment]
@curator 
added at https://github.com/f5devcentral/terraform-provider-bigip/blob/master/website/docs/r/bigip_ltm_persistence_profile_cookie.html.markdown

**Comment by curator** [comment]
I think that might be the wrong spot.  It would more naturally be at https://github.com/f5devcentral/terraform-provider-bigip/blob/master/website/docs/r/bigip_ltm_virtual_server.html.markdown
