### ISSUE TITLE
Add node with desired state (Enabled/Disabled)

### ISSUE THREAD

**Issue by tlian** [f5devcentral/terraform-provider-bigip#67]
At times, it is desired to add the node in 'disabled' state. To do so would require adding "state" attribute
resource "bigip_ltm_node" "node" {
  name = "/Common/terraform_node1"
  address = "10.10.10.10"
  state = "disabled"
}

**Comment by pteiber** [comment]
@tlian, it's interesting you bring this up. I actually have a similar need and was going to start tackling this. It's actually pretty straightforward to implement - you just need to wire the terraform plugin with the go-bigip library. Are you able to implement this? If not, I can add it to my to-do list.

**Comment by pteiber** [comment]
Started working on this today, but ran into another problem with FQDN nodes (see #68).

I'm debating whether or not to use enabled/disabled for this (and the session attribute as well - I need that), rather than user-up/user-down for state and user-disabled/user-enabled for session. The latter is what the CLI and API expect, but those names aren't as intuitive.

Would like @scshitole's opinion since he's the maintainer.

**Comment by tlian** [comment]
@pteiber 
At front end, "enabled"/"disabled" might be the most intuitive. At the API talking point (go-bigip) is what it will get changed to as the API expected. 
Thank you for working on this so quickly.
I was trying a fix (as it seemed pretty straight forward), but was hitting some issue and was going to continue to look at it today.

**Comment by pteiber** [comment]
I agree - I'll try for enabled/disabled. I should be able to pick this up again tomorrow.

And yeah - I thought it was going to be pretty straightforward. There's a bit more to it than I expected.

**Comment by tlian** [comment]
@pteiber 
I think I got it working... (ugly version though)
The issue I had was that I put the fix in ```https://github.com/f5devcentral/go-bigip```
But it was required under ```terraform-provider-bigip/vendor/github.com/f5devcentral/go-bigip/```
For the real fix, I imagine the fix would need to go both places.... to have delivered the same code to two locations is a lot of work and error-prone though (a design that invokes curiosity)..
One of my guess is so that the library is standalone and won't have to deal with any other source of truth...(?)

**Comment by jakauppila** [comment]
If the change is required in the underlying library, then the fix there has to be submitted to https://github.com/f5devcentral/go-bigip and once merged the dependency can be updated within this project.

**Comment by pteiber** [comment]
@jakauppila - You're right. Actually, looking at the vendored go-bigip library, it has diverged quite a bit from the one upstream. It'd probably be worth a separate thread to figure out the best way to merge the local changes upstream and move to a better dependency management system here.

**Comment by tlian** [comment]
By the way, in ```bigip/resource_bigip_ltm_pool.go```
the node name had to be extracted out 
```	if add.Len() > 0 {
		for _, d := range add.List() {
			client.AddPoolMember(name, d.(string))
			node_name := strings.Split(d.(string), "/")
			node_name2 := strings.Split((node_name[len(node_name)-1]), ":")[0]
			client.NodeStatus(node_name2, state)
		}
	}```
because the node name was appended with partition name "/Common/node_name:111" 
Probably useless for you, but wanting to bring it as it tricked me for a few hours : )

**Comment by scshitole** [comment]
@tlian  @pteiber 
added state to node resource, default is "user-up" you can use "user-down" to disable

**Comment by tlian** [comment]
That's awesome! Great work. 

Minor note: 
I think most people would first always take a look at the readme file one the main page
https://github.com/f5devcentral/terraform-provider-bigip

But then, found out that a complete documentation was located here 
https://github.com/f5devcentral/terraform-provider-bigip
