### ISSUE TITLE
Question - Is there a targeted Release Cycle

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/terraform-provider-bigip#69]
Is there a targeted release cycle for the Terraform Provider, other upstream engines release on like 6-8 month cycle, is this something like this we can expect as a consumer?

**Comment by scshitole** [comment]
@jmcalalang Once the provider is published we will have target releases, currently hashicorp is reviewing the code.

**Comment by jmcalalang** [comment]
thanks @scshitole looking forward to the cycle releases!
