### ISSUE TITLE
May I get contributor permission? 

### ISSUE THREAD

**Issue by tlian** [f5devcentral/terraform-provider-bigip#70]

**Comment by jakauppila** [comment]
Anyone should be able to submit a PR to the repo.

**Comment by tlian** [comment]
Did a test push and no permission? 
Thinking was I would need to push a new branch, then request a PR ?

**Comment by pteiber** [comment]
You need to fork this repo, and then push to that. When you create a PR, use your fork as the source.

**Comment by tlian** [comment]
Thank you.
