### ISSUE TITLE
IRules on VIPs are not ordered.

### ISSUE THREAD

**Issue by zaphar** [f5devcentral/terraform-provider-bigip#78]
It looks like IRules are of type `schema.TypeSet` which is unordered. However the execution order for IRules matter. For complicated IRule setups which I have inherited in my current deployment being able to insert an IRule into a particular position in the order would be really helpful.
 Is there a chance we can make IRules ordered for VIPs perhaps by using a `schema.TypeList`?

**Comment by scshitole** [comment]
@zaphar sure let me see how we can do that, will update you.

**Comment by zaphar** [comment]
@scshithole, I actually have a patch adding it to the provider that I'm using for some some testing locally. My one caution here is that I'm not sure what the impact is if you change this with state using the previous set semantics.

If you want I can issue a pull request.

**Comment by scshitole** [comment]
@zaphar sure please go ahead I will test it and if any issue uncommit the PR

**Comment by zaphar** [comment]
@scshitole Ping :-D. I'll be trying some tests for my infrastructure soon with this patch. If you are able to verify on your side as well we can figure out if it will impact users adversely at all.

**Comment by dannyk81** [comment]
Since this was reverted and not merged, could we reopen it and revisit this? as I would probably be hitting the same issue as we go forward 😉

**Comment by zaphar** [comment]
I haven't had free time yet to look at the test failures but I wholly support reopening the issue.
