### ISSUE TITLE
Net Route not persisted in tfstate, causes recreation on subsequent applies

### ISSUE THREAD

**Issue by dannyk81** [f5devcentral/terraform-provider-bigip#82]
Environment details:
```
F5 BIGIP version 12.1.1 build 2.67.204
Terraform v0.10.4
bigip provider built from master
```

Here's our route definition:
```
resource "bigip_net_route" "app_route_dgw" {
  name       = "${format("/%s/app-route-dgw", var.f5_app_partition)}"
  network    = "0.0.0.0/0"
  gw         = "xxx.xxx.xxx.254"
  depends_on = ["bigip_net_selfip.app_selfip"]
}
```

The resource is created succesfully:
```
bigip_net_route.app_route_dgw: Creating...
  gw:      "" => "xxx.xxx.xxx.254"
  name:    "" => "/<partition-name>/app-route-dgw"
  network: "" => "0.0.0.0/0"
bigip_net_route.app_route_dgw: Creation complete after 1s

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

However, we we run a subsequent apply, terraform attempts to Create it again:
```
bigip_net_route.app_route_dgw: Creating...
  gw:      "" => "xxx.xxx.xxx.254"
  name:    "" => "/<partition-name>/app-route-dgw"
  network: "" => "0.0.0.0/0"
Releasing state lock. This may take a few moments...
Error applying plan:

1 error(s) occurred:

* bigip_net_route.app_route_dgw: 1 error(s) occurred:

* bigip_net_route.app_route_dgw: 01020066:3: The requested static route (/<partition-name>/app-route-dgw) already exists in partition <partition-name>.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Using `terraform show` command, we can see all the other resources, but `bigip_net_route.app_route_dgw` is missing:
```
$ terraform show|grep bigip
bigip_ltm_node.blue_ingress_node.0:
bigip_ltm_node.blue_ingress_node.1:
bigip_ltm_node.blue_master_node.0:
bigip_ltm_node.blue_master_node.1:
bigip_ltm_node.blue_master_node.2:
bigip_ltm_pool.blue_kub_ingress_pool:
bigip_ltm_pool.blue_kub_master_pool:
bigip_ltm_snatpool.app_snat_pool:
bigip_ltm_virtual_server.blue_kub_ingress_vip:
bigip_ltm_virtual_server.blue_kub_master_vip:
bigip_net_selfip.app_selfip:
bigip_net_vlan.app_vlan:
```

**Comment by scshitole** [comment]
@dannyk81  yes thats true we should somehow get rid off common, I think I did to read the route-name as the API suggested, let me check the API doc again

**Comment by dannyk81** [comment]
Thanks for replying @scshitole 😄 

Based on a simple test I did, a Route that is created in the `Common` partition must be given the "full path" name to be retrieved via the API, e.g. `/Common/dgw` (otherwise I just get a 404).

**Comment by dannyk81** [comment]
@scshitole I think https://github.com/f5devcentral/go-bigip/pull/9 solves this, please take a look.

**Comment by dannyk81** [comment]
ping @scshitole 🙏

**Comment by dannyk81** [comment]
Sorry for nagging on this @scshitole, but could you take a look please? 😊 

This should fix `bigip_net_route` resource. Unless you have a different approach on how to handle it?

**Comment by dannyk81** [comment]
@scshitole I'm really stuck without fixing this, we have multiple partitions in our setup and I can't use this resource without this fix 😞 

Please take a look at https://github.com/f5devcentral/go-bigip/pull/9 and merge if you agree, if not we can get rid of the extra logic to add the `/Common/` if partition name was not specified and instruct the users to always use the full-path name.
